# Generated by Django 4.2.6 on 2023-10-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('AfiliadoID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, null=True)),
                ('Correo', models.CharField(max_length=45, null=True)),
                ('Telefono', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'Afiliado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AfiliadoVehiculo',
            fields=[
                ('EmpresaPeriodoVeh', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('EmpresaID', models.IntegerField(null=True)),
                ('Per_AA', models.IntegerField(null=True)),
                ('Per_MM', models.IntegerField(null=True)),
                ('VehiculoID', models.CharField(max_length=10, null=True)),
                ('NumVehiculo', models.IntegerField(null=True)),
                ('Placa', models.CharField(max_length=6, null=True)),
                ('NumFirmas', models.IntegerField(null=True)),
                ('TIngresos', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('TEgresos', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('Veh_Area', models.CharField(max_length=1, null=True)),
                ('AfiliadoID1', models.ForeignKey(db_column='AfiliadoID1', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='afiliado1_set', to='api.afiliado')),
                ('AfiliadoID2', models.ForeignKey(db_column='AfiliadoID2', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='afiliado2_set', to='api.afiliado')),
            ],
            options={
                'db_table': 'AfiliadoVehiculos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=6, null=True)),
                ('Fecha', models.DateField(null=True)),
                ('Hora', models.DateTimeField(null=True)),
                ('Vencido', models.BooleanField(default=True)),
                ('Llave', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'Token',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExtractoVehiculo',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('EmpresaID', models.IntegerField(null=True)),
                ('Per_AA', models.IntegerField(null=True)),
                ('Per_MM', models.IntegerField(null=True)),
                ('VehiculoID', models.CharField(max_length=10, null=True)),
                ('NumVehiculo', models.IntegerField(null=True)),
                ('Placa', models.CharField(max_length=6, null=True)),
                ('Nivel0', models.IntegerField(null=True)),
                ('NivelID', models.IntegerField(null=True)),
                ('Nvl_Name', models.CharField(max_length=45, null=True)),
                ('ConceptoID', models.CharField(max_length=10, null=True)),
                ('Cto_Des', models.CharField(max_length=75, null=True)),
                ('ValorBase', models.DecimalField(decimal_places=2, max_digits=12)),
                ('PorBase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porCal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ValorIng', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ValorEgr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Ref1', models.IntegerField(null=True)),
                ('Ref2', models.IntegerField(null=True)),
                ('Ref3', models.IntegerField(null=True)),
                ('EmpresaPeriodoVehID', models.ForeignKey(db_column='EmpresaPeriodoVehID', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.afiliadovehiculo')),
            ],
            options={
                'db_table': 'ExtractoVehiculo',
                'managed': True,
            },
        ),
    ]

