# Generated by Django 4.2.6 on 2023-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='Correo2',
            field=models.CharField(max_length=45, null=True),
        ),
    ]

