# Generated by Django 4.2.5 on 2023-10-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_afiliado_correo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractovehiculo',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
