# Generated by Django 4.2.5 on 2023-11-17 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_extractovehiculo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Radicado', models.CharField(max_length=16, null=True)),
                ('Fecha', models.DateField(null=True)),
                ('Hora', models.DateTimeField(null=True)),
                ('Estado', models.BooleanField(default=True)),
                ('Detalle', models.CharField(max_length=355, null=True)),
                ('AfiliadoPQRID', models.ForeignKey(db_column='AfiliadoPQRID', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.afiliado')),
            ],
            options={
                'db_table': 'PQR',
                'managed': True,
            },
        ),
    ]
