# Generated by Django 4.2.5 on 2023-11-24 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_destinatariopqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqr',
            name='DestinatarioPQRID',
            field=models.ForeignKey(blank=True, db_column='DestinatarioPQRID', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.destinatariopqr'),
        ),
    ]
